server:
  port: 8088

app:
  config:
    aws:
      region: us-east-1
      access_key_id: xxxxxx
      secret_key_id: xxxxxx
      message:
        queue:
          topic:
            url: xxxxxx
            name: xxxxxx
          max_number_messages_polling: 10
          wait_time_second_polling: 1